export const gbpLocation = {
  storeName: "Indigenous Midtown Cannabis",
  domain: "www.indigenousmidtowncannabis.ca",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "93 Broadway Ave, Toronto, ON M4S 2A2",
  streetAddress: "93 Broadway Ave",
  postalCode: "M4S 2A2",
  phone: "+1 (437) 219-7367",
  phoneIntl: "+14372197367",
  neighborhood: "Broadway / Yonge–Eglinton Midtown",
  nearbyAreas: ["Midtown Toronto", "Yonge and Eglinton", "Broadway Avenue", "Redpath Avenue", "Davisville", "Eglinton Avenue", "North Toronto", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "/visit",
  mapEmbedUrl: "",
  latitude: "43.7104899",
  longitude: "-79.3935826",
  hours: ["Open 24 Hours"],
  seoTitle: "Indigenous Midtown Cannabis | Broadway Walk-In at Yonge–Eglinton",
  metaDescription: "Indigenous Midtown Cannabis is an adult 19+ walk-in at 93 Broadway Ave in Midtown Toronto near Yonge–Eglinton and Redpath. Open 24 Hours.",
  localLandmarks: ["Broadway Avenue", "Yonge and Eglinton", "Redpath Avenue"],
  introVariant: "Indigenous Midtown Cannabis is a local weed dispensary at 93 Broadway Ave, one block north of Eglinton near Redpath Avenue. Adults 19+ can browse flower tiers and category pages for pre-rolls, edibles, vapes, concentrates, and accessories before visiting.",
  neighborhoodDescription: "The storefront sits on Broadway Avenue in the Yonge–Eglinton Midtown grid, surrounded by local retail and a short walk from Eglinton Station on Line 1.",
  parkingNote: "Street parking on Broadway Avenue; evening curb space is often easier than midday. Read posted signs.",
  transitNote: "A short walk from Eglinton Station on Line 1. Walk north to Broadway Avenue, then east toward Redpath.",
  sectionTitle: "Serving walk-in customers on Broadway near Yonge–Eglinton"
};
