export const gbpLocation = {
  storeName: "Indigenous Midtown Cannabis",
  domain: "www.indigenousmidtowncannabis.ca",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "93 Broadway Ave, Toronto, ON M4S 2A2",
  streetAddress: "93 Broadway Ave",
  postalCode: "M4S 2A2",
  phone: "+1 (437) 219-7367",
  phoneIntl: "+14372197367",
  neighborhood: "Midtown Toronto / Yonge and Eglinton / Mount Pleasant",
  nearbyAreas: ["Midtown Toronto", "Yonge and Eglinton", "Mount Pleasant", "Davisville", "Eglinton Avenue", "Leaside", "Moore Park", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.7077",
  longitude: "-79.3948",
  hours: ["Open 24 Hours"],
  seoTitle: "Indigenous Midtown Cannabis | Weed Dispensary in Toronto",
  metaDescription: "Indigenous Midtown Cannabis is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Midtown Toronto", "Yonge and Eglinton", "Mount Pleasant"],
  introVariant: "Indigenous Midtown Cannabis is a local weed dispensary at 93 Broadway Ave near Midtown Toronto, Yonge and Eglinton, and Mount Pleasant. Adults 19+ can browse flower tiers and category pages for pre-rolls, edibles, vapes, concentrates, and accessories before visiting.",
  neighborhoodDescription: "Located in the vibrant Midtown Toronto / Yonge and Eglinton / Mount Pleasant district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking and public parking garages are nearby",
  transitNote: "A short walk from Eglinton subway station and served by local TTC routes.",
  sectionTitle: "Serving Customers Near Midtown Toronto and Yonge-Eglinton"
};
