// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Indigenous Midtown Cannabis",
  domain: "indigenousmidtowncannabis.ca",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "93 Broadway Ave, Toronto, ON M4S 2A2",
  streetAddress: "93 Broadway Ave",
  postalCode: "M4S 2A2",
  phone: "(437) 870-3710",
  phoneIntl: "+14378703710",
  neighborhood: "Midtown Toronto / Yonge and Eglinton / Mount Pleasant",
  nearbyAreas: ["Midtown Toronto", "Yonge and Eglinton", "Mount Pleasant", "Davisville", "Eglinton Avenue", "Leaside", "Moore Park", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://maps.google.com/?q=93+Broadway+Ave,+Toronto,+ON+M4S+2A2",
  mapEmbedUrl: "https://maps.google.com/maps?q=Indigenous%20Midtown%20Cannabis%2093%20Broadway%20Ave%2C%20Toronto%2C%20ON%20M4S%202A2&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.7077",
  longitude: "-79.3948",
  hours: ["Open 24 Hours"],
  seoTitle: "Indigenous Midtown Cannabis | Weed Dispensary in Toronto",
  metaDescription: "Indigenous Midtown Cannabis is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Midtown Toronto", "Yonge and Eglinton", "Mount Pleasant"],
  introVariant: "Indigenous Midtown Cannabis is your welcoming neighborhood weed dispensary in Toronto, located at 93 Broadway Ave near Midtown Toronto / Yonge and Eglinton / Mount Pleasant. We carry a massive selection of weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and smoking accessories for adults 19+. Conveniently located near Yonge and Eglinton, our cannabis store and weed shop is designed to make finding the perfect strain easy and accessible.",
  neighborhoodDescription: "Located in the vibrant Midtown Toronto / Yonge and Eglinton / Mount Pleasant district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking and public parking garages are nearby",
  transitNote: "A short walk from Eglinton subway station and served by local TTC routes.",
  sectionTitle: "Serving Customers Near Midtown Toronto and Yonge-Eglinton"
};
